[tool.poetry]
name = "DevOps-Course-Starter"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
pylint = "^2.5.3"
python-dotenv = "^0.14.0"
pyyaml = "^5.3.1"
requests = "^2.24.0"
rope = "^0.17.0"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
selenium = "^3.141.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
